### ISSUE TITLE
OWF ToolBar is not showing up

### ISSUE THREAD

**Issue by buutran** [ozoneplatform/owf-framework#17]
Hello Experts,
I am so new to OWF. I installed OWF with localhost option and connect to database, it worked fine. But after changing the localhost to servername (generated server certs and user cert by following the instruction). I was able to login to servername:8443/owf/ by testAdmin1/password but OWF ToolBar wont show up any more! Please Help
Thanks so much

**Comment by rpokorny** [comment]
Most likely either a configuration issue or a duplicate of #25.  Closing.
