### ISSUE TITLE
OWF.Launcher.launch fails when used by a Background Widget

### ISSUE THREAD

**Issue by UberGeekxor** [ozoneplatform/owf-framework#18]
When a background widget calls the `OWF.Launcher.launch` function an exception occurs in the `launchWidgetInstance` function of [js/components/dashboardDashboard.js](https://github.com/ozoneplatform/owf/blob/master/web-app/js/components/dashboard/Dashboard.js). `Ext.getCmp(sender.id)` returns `null` for a background widget so attempt to access `pane` property fails and script stops execution.

Issue was discovered when investigating a question from the [ozoneplatform-users Google Group](https://groups.google.com/d/msg/ozoneplatform-users/wetgT6vS_PU/u8CKcuJMUrUJ).

**Comment by rpokorny** [comment]
Appears to be fixed, probably by the linked commit.  Closing.
