### ISSUE TITLE
Ozone behind a reverse proxy/SSO

### ISSUE THREAD

**Issue by MattPark** [ozoneplatform/owf-framework#36]
I'm trying to get a development version of ozone working behind our reverse proxy.
Basically, the externally facing Apache instance handles PKI authentication and then passes an HTTP header back such as REMOTE_USER.
````
[User] ---------HTTPS--------->[Proxy]---------------HTTP--------------->[Ozone]
             └--PKI-CERT--┘                  └--REMOTE_USER--┘
````
For this to work, ozone should not be running with SSL, since the traffic is running with SSL from the externally facing machine to the user.  It looks as though running Ozone with HTTP (non-SSL) is unsupported, although I think this would be the preferred method when running with any single sign on scenario.

How can I run ozone without SSL and are there any default security profiles for getting the authentication info from a header?

**Comment by ericavijay** [comment]
Hello Matt,

Did you ever get this working completely? 

Regards
Vijay

**Comment by MattPark** [comment]
Yeah I got it working fine, and intended to contribute the code, but the way that the project was laid out I couldn't figure out where to put the Spring module.  I don't have the code any more at this point.
