### ISSUE TITLE
Proposed clarification of widget intents data payload to support ability to send optional data

### ISSUE THREAD

**Issue by tinaColemanNextCentury** [ozoneplatform/owf-framework#38]
We have a use case in which we'd like to send over optional information in an intent.  If the user selects a widget that can make use of the additional information, it will, but otherwise the intent specifies a basic behavior.  This is modeled today in Android intents - see their description of [extras] (http://developer.android.com/guide/components/intents-filters.html#extras).

More specific use case for widgets: assume that we'd like to plot KML. Type would be "application/kml" and action requested ACTION_VIEW.  Optimally, any widget that can support KML viewing would be able to handle.  That said, I'd like to consider use cases where I specify a layer in which to put the KML, for maps that can handle.  (This is a supported capability in CMWAPI-compliant maps...).  I'd like to pass along a layer id as an optional bit of metadata to be used by maps which can support it...

Proposed patch file included below, underneath the dashed line.  (Note: although it is possible to set up pull requests for wikis, the owf.wiki project has some issues with duplicate files in its trees, so I was unable to push to a new repo for use with a pull request.)

Understood impact: none.  The wiki updates suggest an approach, but do not require it.  The updated text is intended to just more strongly state what the examples provided by the team already imply.

--------------------------------------------------------------------------------------------------------------------
From 2835c25dfcba0674a2387b6b2170d81414d545a7 Mon Sep 17 00:00:00 2001
From: Tina Coleman <tina.coleman@nextcentury.com>
Date: Fri, 27 Dec 2013 16:04:24 -0500
Subject: [PATCH] Proposed update to clarify means for extension for widget
 intents

---
 OWF7/OWF-7-Developer-Widget-Intents-API.md | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/OWF7/OWF-7-Developer-Widget-Intents-API.md b/OWF7/OWF-7-Developer-W
index 9174b3b..b2467ec 100644
--- a/OWF7/OWF-7-Developer-Widget-Intents-API.md
+++ b/OWF7/OWF-7-Developer-Widget-Intents-API.md
@@ -1,3 +1,4 @@
+
 #   Widget Intents API
 #1   Overview

@@ -54,7 +55,7 @@ The Widget Intents API requires the use of Eventing. For an ex
 Use the Widget Editor in the user interface to add, edit or remove widget inten

 1. The first argument is **an Intent**. An Intent is simply an object describin
-2. The second argument is **an object containing the data** that the intent is
+2. The second argument is **an object containing the data** that the intent is
 3. The third argument is **a callback function** that is executed once the rece

 The example below displays an intent that graphs a stock price. Once a receivin
@@ -91,7 +92,7 @@ Use the Widget Editor in the user interface to add, edit or re

 1. The first argument is **an Intent**. An Intent is simply an object describin

-2. The second argument, **a function** that is executed once an Intent is recei
+2. The second argument, **a function** that is executed once an Intent is recei

 The example below uses Intents to plot a stock price on the graph:

--
1.7.11.msysgit.1

**Comment by rpokorny** [comment]
The formatting on the patch file doesn't appear to have come through correctly, so I can't really tell what it is trying to show.  If this is still important to you, please submit again as a PR.
