### ISSUE TITLE
Update 7.0 documentation

### ISSUE THREAD

**Issue by spyhunter99** [ozoneplatform/owf-framework#39]
The current quick start guide no longer matches the content of the distribution zip. It basically says to unzip OWF-bundle-7-GA.zip, cd to apache tomcat and run.

There's no bundle zip and the distribution no longer has apache tomcat on it. Where's the server? If it's not supposed to be in the bundle, can you at least some add some basic build/deploy instructions?

Also v6 is also missing the tomcat bundle

**Comment by stephanieerin** [comment]
I've uploaded bundles to the releases section on this repo, any future updates will be released with an apache tomcat bundle.
