### ISSUE TITLE
Proposed documentation contribution: deploying to new server

### ISSUE THREAD

**Issue by tinaColemanNextCentury** [ozoneplatform/owf-framework#40]
The Configuration Guide speaks to running from a new port, but not from running from something other than localhost.  See https://github.com/tinaColemanNextCentury/owf-wiki/commit/80fe9e914cde31e39a18703f89a925f53c6d48b4

As an aside, attempting to contribute via guidance on http://fusiongrokker.com/post/how-you-can-contribute-to-taffy-documentation, as vetted by gollum team at https://github.com/gollum/gollum/issues/265.

**Comment by rpokorny** [comment]
Merged
