### ISSUE TITLE
Named dashboard regions / launch widget to region

### ISSUE THREAD

**Issue by brian428** [ozoneplatform/owf-framework#42]
As described in the Google Group (at https://groups.google.com/forum/#!topic/ozone-developers/gH7qd19eLyc as well as previous threads from other folks), we're looking for an option to name dashboard regions, and then launch a new widget into a specific region.

**Comment by rpokorny** [comment]
At this point we don't plan to add new features to OWF.  Please see OZP for the next-gen of Ozone platforms.

As additional dashboard capabilities are added to OZP, we will keep the idea of named panes in mind.
