### ISSUE TITLE
New dashboard region type: Navigation (or Toolbar)

### ISSUE THREAD

**Issue by brian428** [ozoneplatform/owf-framework#43]
Some of the other issues I just created (https://github.com/ozoneplatform/owf/issues/41 and https://github.com/ozoneplatform/owf/issues/42) would become partly unnecessary if OWF supported a way to define a dashboard region to act as a pre-defined navigation area.

Similar to the way Ext JS Toolbars work, a Navigation region could be docked to the left or top of a dashboard. Menu options would allow launching new widgets into the other dashboard area(s).

This may require some thought. Ideally, it would work exactly like an Ext JS Toolbar, to not only limit the space it uses on the dashboard, but also to remove any frame overflow issues. (Currently, a widget providing navigation control would require enough space to show any drop down menus, otherwise they're cut off at the edge of the frame).

I'm not sure if the best way to configure this navigation toolbar would be though a JSON object, or if a URL could be given to OWF to define the items and behavior of the toolbar, or if some other approach would be better. But given how complex OWF dashboards can become, especially when many widgets are available, it really needs an option for more focused navigation and control over the widgets and the inter-widget workflows they enable.

**Comment by rpokorny** [comment]
At this point we don't plan to add new features to OWF.  Please see OZP for the next-gen of Ozone platforms.
