### ISSUE TITLE
PostgreSQLPrefsInitialCreate.sql primary key collisions

### ISSUE THREAD

**Issue by ruckc** [ozoneplatform/owf-framework#53]
When using `PostgreSQLPrefsInitialCreate.sql`, the hibernate_sequence starts at 1.  When it loads the default app components for the administration app, they have hardcoded 186-195 identifiers.  Whenever hibernate_sequence overlaps those, the objects will fail to create with hibernate primary key collision errors.

I locally fixed my postgresql script by changing the hardcoded id's to `nextval('hiberate_sequence')`

**Comment by ruckc** [comment]
Your have a similar problem with the Oracle script also.

**Comment by ruckc** [comment]
And mysql... for some reason SQL Server doesn't have the problem.

**Comment by stephanieerin** [comment]
What are you doing to see this error consistently? We've had a hard time pinpointing it in MySql.

**Comment by qotho** [comment]
The upgrade scripts are resetting "hibernate_sequence" to 200.  This should only be happening on the initial creation scripts.  Resetting it for an existing database causes collisions.

**Comment by stephanieerin** [comment]
Got it. Thanks!
