### ISSUE TITLE
User's don't get widgets with external group changes.

### ISSUE THREAD

**Issue by qotho** [ozoneplatform/owf-framework#57]
If I alter a user's group membership outside of OWF (like LDAP), the membership change is detected and made by SecurityFilters. Meaning, if I go into the "Users" widget and look at the user's groups, they are correct, but the user does not get the widgets associated with a newly added group or lose them when a group is removed from the user. 

This is because there are no person_widget_definition records created for the user.  If I manually remove any group through the OWF admin UI, and re-add it, the widgets show up.  I compared the person_widget_definition table before and after doing this, and the person_widget_definition records aren't there before, and they get added after I remove and re-add the group. Records seem to be added for all widgets, not just those associated with the group I modified.

**Comment by qotho** [comment]
It looks like the problem is generally related to the "sync" related changes, seen in the following commit:

https://stash.di2e.net/projects/OWFGOSS/repos/aml-owf/commits/546845b03a246551a0fddf6cde06d78ec93c5293#grails-app/controllers/ozone/owf/grails/controllers/ConfigController.groovy

Specifically, the user's groups are updated on login in SecurityFilters.  In 7.14.2, there used to be a call in ConfigController that caused the person_widget_definition records to be updated for the user, based on their updated group membership.  This functionality was moved.

The problem is that the call in ConfigController was never replaced. So even though SecurityFilters updates a user's group memberships, nothing syncs the person_widget_definition records after login. Manually adding or removing a group for the user causes a sync to happen, which "fixes" the problem.

In the commit linked below, I added a call to "AccountService.sync", in SecurityFilters, to force the person_widget_definition records to be synchronized, only if a user's group memberships have changed. This seems to fix the issue.

https://github.com/qotho/owf-framework/commit/8af7be42a5a7cb45f9f9e62a5f4340ededfe4b2e

**Comment by stephanieerin** [comment]
This looks good, thanks for doing so much digging! If you want to submit a PR for your changes I'll test it out and merge it in.

**Comment by qotho** [comment]
I saw the instructions for contributing that you committed.  I don't have privileges to create a branch in this repository.  Do you want me to just do a PR from my fork?

**Comment by stephanieerin** [comment]
Yeah, that’s fine. I’ll update the contributing guidelines too, I meant to say create a fork.

Stephanie
