### ISSUE TITLE
Verify that OWF does not use the dojo content handler for javascript

### ISSUE THREAD

**Issue by mparizernc** [ozoneplatform/owf-framework#64]
The following is included in OWF as part of dojo. The code should never be used/called by OWF this ticket is to validate that is accurate.

Dynamic Code Evaluation: Code Injection within the dojo content handler for javascript, on the same line number (9899) in all three files (owf-server.js, owf-widget.js, and owf-admin-widget.js)

       9895        javascript: function(xhr){ 
       9896            // summary: A contentHandler which evaluates the response data, expecting it to be valid JavaScript
       9897
       9898            // FIXME: try Moz and IE specific eval variants?
       9899            return _d.eval(xhr.responseText);
       9900        },     

The file owf-widget.js interprets unvalidated user input as source code on line 9899. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

**Comment by rpokorny** [comment]
I have verified that OWF does not appear to use this function.
