### ISSUE TITLE
Eventing and the relay file

### ISSUE THREAD

**Issue by moorena** [ozoneplatform/owf-framework#65]
The ["adding eventing"](https://github.com/ozoneplatform/owf-framework/wiki/OWF-7-Developer-Adding-Eventing-API-to-Widget) section mentions copying the relay file to your webapp folder, and then setting the OWF.relayFile variable to point the webapp location.

We host our widgets under an OWF instance, so the relay file exists under https://localhost:8443/owf/js/eventing/rpc_relay.uncompressed.html . We do not set the OWF.relayFile (or Ozone.eventing.Widget.widgetRelayURL), but eventing pub/sub still works fine. Looking into the code, it appears there's a default of [context]/js/eventing/rpc_relay.uncompressed.html  (in owf-widget.js).

The documentation implies you must do the relayFile set up. Are we doing something wrong by not setting the relayFile variable and relying on the default ? Are there things that may break otherwise ? (We have not found any problems, and have been deployed for quite some time)

**Comment by rpokorny** [comment]
The relay file is only used in browsers that do not support the postMessage 
API.  Of the browsers that OWF supports, IE7 is the only one in that category.  
Therefore unless you are supporting IE7, the relay file is actually totally 
unnecessary.  

Additionally, if your widgets are all deployed on the same domain as each 
other and as the OWF container, as it sounds like they are, then the relay file 
will not be used.

**Comment by moorena** [comment]
Thanks for that clarification. Could that note be added to the docs as well ? (that the relay file is an IE7 workaround)

**Comment by rpokorny** [comment]
The documentation page that you referenced has been updated.  Closing this ticket.
