### ISSUE TITLE
7.17.0-BETA5 - Rest Documentation missing stylesheets

### ISSUE THREAD

**Issue by ruckc** [ozoneplatform/owf-framework#67]
In 7.17.0-BETA5 the rest documentation can't load /rest/css/bootstrap.css /rest/css/main.css and /rest/css/solarized_light.css

Also, it tries to load jquery.min.js from https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js which doesn't always work...

**Comment by rpokorny** [comment]
CSS issue fixed in 5390bc6.

I consider the jquery issue to be a Won't Fix.  If it fails to load from that remote URI it falls back to a local copy of jquery.
