### ISSUE TITLE
REST API nonsense.

### ISSUE THREAD

**Issue by ruckc** [ozoneplatform/owf-framework#68]
Looking at the REST api, I have a few frustrations that I'd like to vent on.  I've been dealing with various REST apis for over a decade and OWF seems to have the only API that doesn't make logical sense.  Also, as I doubt a 7.18 can fix any of this in any decent timeframe I'd actually prefer it didn't change unless an improved API was independent of this one.

1) In typical RESTful APIs the web service should provide the same format of data as it consumes.  The fact that the JSON structure of widgets from `GET /widget` being different from what you `POST`/`PUT` to /widget is extremely frustrating.

1.1) Why are their different fields in the POST/PUT and not in the GET... such as `allRequired` and `directRequired`?

1.2) Why does the GET request have fields that appear extremely duplicative such as `image`, `headerIcon`, `smallIconUrl`, `mediumIconUrl`?  The database only has two icon fields...

1.3) What is the difference from `definitionVisible` and `visible`?  They look to always change together, is this another field duplication?

2) widget_types and tags, why am I putting the entire widget_type object or tag object in the `POST`/`PUT` to create a new widget?  Wouldn't it be simpler if I could just say `widget_types: ['administration','standard']`?  Same as `tags: ['map']` versus `tags: [{'id':1,name:'map',...}]`

3) `DELETE /prefs/widgetDefinition` ... Why do I have to send the entire widget object to delete the definition?  Is the ID not enough?

4) `DELETE /widget` .... Why do I have to send the entire widget object to delete it?  Is the ID not enough?

**Comment by rpokorny** [comment]
We agree that the REST API in OWF is far from ideal.  You may want to look into the API exposed by OZP, the next-generation Ozone product which is meant to replace OWF and Marketplace.  You will hopefully find that API to be much cleaner.
