### ISSUE TITLE
Source '/usr/share/tomcat6' or destination '/var/log/cef' are invalid directories.

### ISSUE THREAD

**Issue by ruckc** [ozoneplatform/owf-framework#69]
2015-12-11 17:13:47,714 ERROR [org.ozoneplatform.auditing.quartz.jobs.AbstractFileMovementJob] (quartzScheduler_Worker-4) Source '/usr/share/tomcat6' or destination '/var/log/cef' are invalid directories.

Where is this configured at?

**Comment by rpokorny** [comment]
Within the Configuration Page of the Administration App.  Go to the Auditing section and there will be a number of relevant settings as described below:


"Common Event Format (CEF) Auditing" - This is on by default; turn it off if you do not need audit logs that record all modifications to persisted data

"Object Access Auditing" - This is off by default; turn it on to log all ACCESSES of persisted data to the CEF logs.  This produces very verbose output

"Relocate CEF Logs" - This flag, which is on by default, activates a job which runs periodically to export CEF logs to a separate directory on the system.  This is used in conjunction with other tools which watch for logs deposited in a particular directory.  If you are not using such a system this should be turned off - this should fix the error that you are seeing.

"CEF Log Source Location"
"CEF Log Destination Location" - The directories which the relocation job uses for the logs.  If you want the job to run, but just need it to use different directories, then these are the parameters to adjust.
