### ISSUE TITLE
OWF 7.16 Custom Banners Not Working

### ISSUE THREAD

**Issue by jillson** [ozoneplatform/owf-framework#71]
Per https://github.com/ozoneplatform/owf-framework/wiki/OWF-7-Configuring-Custom-Banners, setting custom banners is a matter of setting (in OwfConfig.groovy) something like:
customHeaderFooter {
        header = 'location/within/web/server/root/example.html'
        headerHeight = 14
        footer = 'location/within/web/server/root/example.html'
        footerHeight = 14
        jsImports = ['location/within/web/server/root/exampleImport1.js',
                          ' location/within/web/server/root/exampleImport2.js']
        cssImports = [' location/within/web/server/root/    exampleImport1.css',
                           ' location/within/web/server/root/exampleImport2.css']
    }

And in previous versions of OWF 7, that worked just fine.
Looking at to https://github.com/ozoneplatform/owf-framework/blob/v7.16.1/src/groovy/ozone/owf/enums/OwfApplicationSetting.groovy,
[and also ./grails-app/services/ozone/owf/grails/services/CustomHeaderFooterService.groovy which uses the same], it seems like the format changed to something more like:

custom.footer.url = 'OWF_footer.html'
custom.footer.height = 14
custom.header.url = 'OWF_header.html'
custom.header.height = 14

I've tried both; no headers, and looking at the config.js, I see:

"custom":{"footer":{"url":"OWF_footer.html","height":14},"header":{"url":"OWF_header.html","height":14}},"customHeaderFooter":{"header":"","headerHeight":0,"footer":"","footerHeight":0,"jsImports":[],"cssImports":[]},

Did a change get half made or am I missing something else?

**Comment by mparizernc** [comment]
Sorry, it appears the wiki is out of date.  If you view the OWF Administrator's Guide found at https://github.com/ozoneplatform/owf-omp-docs/blob/master/OWF%20Administrator's%20Guide.doc in section 2.3.3 it will explain how to configure custom headers and footers.  The ability to configure them was moved to the front end and removed from the groovy file.

**Comment by jillson** [comment]
Thanks.  Going to mark this closed
