### ISSUE TITLE
Invalid dependency resolution 

### ISSUE THREAD

**Issue by andrewshannoncsra** [ozoneplatform/owf-framework#72]
Just pulled down the latest of the owf-framework and it cannot resolve the smack.jar 3.3.1 as it points to a repository that has since been shutdown: 

Error |
Resolve error obtaining dependencies: The following artifacts could not be resolved: org.igniterealtime.smack:smack:jar:3.3.1, org.igniterealtime.smack:smackx:jar:3.3.1: Could not transfer artifact org.igniterealtime.smack:smack:jar:3.3.1 from/to repository_opencastproject_org_nexus_content_repositories_public (http://repository.opencastproject.org/nexus/content/repositories/public): Service Unavailable (503) (Use --stacktrace to see the full trace)

See:  https://groups.google.com/a/opencast.org/forum/#!topic/matterhorn/sGpkKQNwiMY

**Comment by rpokorny** [comment]
I have just pushed a commit to master that adds the missing dependencies directly to the lib directory, since I can't find them on any currently-running public maven instance.  If you are trying to build a prior release, cherry-pick commit 4720c5e before building in order to get the fix.
