### ISSUE TITLE
Creating a new widget and publishing it to marketplace.

### ISSUE THREAD

**Issue by ericavijay** [ozoneplatform/owf-framework#74]
Hello OWF team,

I have worked on using API, Bootstrap (Twitter) tables, D3 framework to create a widget that can be used to view NetFlow SiLK data  https://tools.netsa.cert.org/silk/index.html - Is there a way I can publish it so rest of the DOD community can use it to display netflow data?

I have built it as a standalone HTML widget as the API calls are all from a webservices layer from Python/Apache server.  The documentation for creating widget looks old and not relevant for OWF 7 - so if you let me know what is the best way I will follow your guidelines get this to your team!

Regards
Vijay

**Comment by rpokorny** [comment]
The DOD being what it is, there aren't really any publicly discuss-able places to publish your widget that I am aware of.  Your best bet is to get the word out about your widget via your own DOD contacts.
