### ISSUE TITLE
Resizing Widget in code

### ISSUE THREAD

**Issue by DTalpas** [ozoneplatform/owf-framework#77]
I do not see any mentions of the ability to programmatically change the height and width of a widget in the developer's guide.  

Is this not possible in OWF?  

Simply resizing the window in js spawns some very interesting events.

If there is a way to resize  a widget in code, please help!

Thanks!

**Comment by rpokorny** [comment]
No, there is not a way for a widget to resize itself programmatically.  Depending on the type of layout that the widget is running in (desktop vs. accordion vs. fit etc), programmatic resize may or may not even make sense.  

For the future, please ask support and widget development questions on the Google Group (https://groups.google.com/forum/#!forum/ozoneplatform-users) and reserve these github tickets for bug reports and new feature requests.
