### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by callesto** [ozoneplatform/owf-framework#79]
/owf/js-lib/jquery-ui-1.10.3/themes/base/jquery.ui.resizable.css Failed to load resource: the server responded with a status of 404 (Not Found)  -  Index:76

Contents of base:
  |_ images
  |_ minified

**Comment by jillson** [comment]
Seeing same issue with OWF 7.16.1 bundle

**Comment by rpokorny** [comment]
Fixed in 9b567fd93a0fcde17
