### ISSUE TITLE
Synchronous XMLHttpRequest warning when Access Alert is dismissed

### ISSUE THREAD

**Issue by rpokorny** [ozoneplatform/owf-framework#81]
Steps to reproduce:

1. Make sure that your browser dev tools are open to the Console tab
2. Log into an instance of OWF that has the Access Alert enabled.
3. Click the OK button on the Access Alert

Expected Results: the Access Alert is dismissed and the rest of the app loads.  No errors in the dev console
Actual Results: Everything loads as it should but the following warning appears in the dev console:

"Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

**Comment by rpokorny** [comment]
Fix committed; pending testing

**Comment by mparizernc** [comment]
Verified in Chrome, FF and IE the console error no longer appears.
