### ISSUE TITLE
7.17.1 potential Bug in Locking Dashboards (apps)

### ISSUE THREAD

**Issue by DTalpas** [ozoneplatform/owf-framework#85]
I think I have found a bug in the locking of dashboards:

User 1 creates dashboard and shares it.

Admin gives access to User 2 (by way of groups).

User 2 loads dashboard and dashboard is unlocked.

User 1 (the dashboard owner), locks the dashboard and then shares it.

User 2 refreshes page, dashboard remains unlocked.

User 2 restores the dashboard and the dashboard is UNLOCKED.

Is this a bug, or am I missing something?

Thanks!!

**Comment by rpokorny** [comment]
That does sound like it would be a bug.  Thanks for finding it.

**Comment by DTalpas** [comment]
If it helps, we are configured to use ldap security option, if you need any details please let me know!

**Comment by mparizernc** [comment]
The fix has been verified, dashboard sharing now keeps the dashboard locked when the setting is set and a restore happens.
