### ISSUE TITLE
Example Channel Listener scrolling not working and too many messages cause slowdown of OWF.

### ISSUE THREAD

**Issue by ssdhaliwal** [ozoneplatform/owf-framework#92]
Open Channel Listener and add channels for capturing data.
After sometime, when the data builds - the entire OWF starts to slow down.
Also, the scroll bar does not work, so only the visible items are selectable.
We can duplicate the problem every time with different data.

**Comment by kdrumm** [comment]
The Channel Listener is intended for demonstration purposes and is not meant to be a production level widget.  If you need a widget for more capabilities, we recommend creating one or modifying the existing code.

**Comment by ssdhaliwal** [comment]
Two things - 1) dont release code with problems if you are not going to support it and
2) when someone reports an issue take it for review, otherwise stop
soliciting feedback.

-- corrected sarcasm in my response - not needed.

**Comment by tpanningnextcen** [comment]
How many messages (and what size) are needed to trigger this problem?

**Comment by ssdhaliwal** [comment]
Following three issues are consistent (both Windows/Linux) and Chrome/Firefox.

1/ the message grid scrolling stop working after approx 50 messages
2/ could not pause the script to do trace because the browser goes into a freeze (non-responsive) for couple of minutes (not seconds) and then all OWF functions slow down
3/ clear the queue returns the operation back to normal - until the next set of messages accumulate.

The message size is not the problem because it occurs with small message payloads (under 100 bytes) and large

Thanks.

**Comment by tpanningnextcen** [comment]
Here's a widget that generates 100 messages of 200 bytes each, and the Channel Listener seems to handle those messages fine. Can you let me know if it triggers the problem on your machine? If it runs fine, can you modify this code to reproduce the problem you're seeing?

The path assumes that it is in the same directory as ChannelListener.gsp, but you can put it somewhere else so long as you change the script src to point to the OWF JavaScript

    <html>
    <head>
    	<script type="text/javascript" src="../../../js-min/owf-widget-debug.js"></script>

        <script type="text/javascript">
            var CHANNEL = 'testchannel';
            var MESSAGE_SIZE = 200;
            var NUM_MESSAGES = 100;
            var WAIT_TIME_MS = 10;

            function broadcastMessages() {

                var message = '';
                for (var byte = 0; byte < MESSAGE_SIZE; ++byte) {
                    message += byte % 10;
                }

                var sendMessageAndWait;
                sendMessageAndWait = function(messagesSent) {
                    OWF.Eventing.publish(CHANNEL, message);
                    if (messagesSent < NUM_MESSAGES) {
                        setTimeout(sendMessageAndWait, WAIT_TIME_MS, messagesSent+1);
                    }
                };
                sendMessageAndWait(0);
            }
        </script>
    </head>
    <body>
        Channel: testchannel
        <button onClick="broadcastMessages();">Send Messages</button>
    </body>
    </html>

**Comment by ssdhaliwal** [comment]
Tom, thanks - should have done the test harness to find the issue.

Looks like this is related to message size and # of messages and how the grid is handling the scrolling.  Grid slows down after about 100+ messages.  For a sample widget I am not worried about, but it does not work for extensive use as testing.

Your test did show - message size is a problem; which I could not capture because browser was freezing by that time and we thought it was our widget doing the problem.

Don't worry about this example, we will build our test harness to capture and track messages for integration testing.

=================================================================================
Updated below to add msg_count into the message; it starts slowing down after 80.

<html>
<head>
	<script type="text/javascript" src="../../../js-min/owf-widget-debug.js"></script>

    <script type="text/javascript">
        var CHANNEL = 'testchannel';
        var MESSAGE_SIZE = 200;
        var NUM_MESSAGES = 500;
        var WAIT_TIME_MS = 10;
        var MSG_COUNT = 0;

        function broadcastMessages() {

            var sendMessageAndWait;
            sendMessageAndWait = function(messagesSent) {
	      var message = (MSG_COUNT++) + "/";
	      for (var byte = 0; byte < MESSAGE_SIZE; ++byte) {
		  message += byte % 10;
	      }

	      OWF.Eventing.publish(CHANNEL, message);
                if (messagesSent < NUM_MESSAGES) {
                    setTimeout(sendMessageAndWait, WAIT_TIME_MS, messagesSent+1);
                }
            };
            sendMessageAndWait(0);
        }
    </script>
</head>
<body>
    Channel: testchannel
    <button onClick="broadcastMessages();">Send Messages</button>
</body>
</html>
